import type { Metadata } from "next";
import { Oswald } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const oswald = Oswald({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-oswald',
});

export const metadata: Metadata = {
    title: 'Fit Log',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html
            lang="en"
      className={`${oswald.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
                <Navbar />
                {children}
            </body>
        </html>
    );
}